name: Linux

on:
  push:
    branches:
      - main
      - release/**

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo +stable build --release --target=x86_64-unknown-linux-gnu
